import { useNavigate } from "react-router-dom";
import { useHealth } from "@/hooks/use-health";
import { LoadingState } from "@/components/loading-state";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

/** Helper to pass CSS custom properties through React's strict style typing. */
function cssProps(props: Record<string, string | number>): React.CSSProperties {
  return props as React.CSSProperties;
}
import { APP_NAME, APP_VERSION, ROUTES } from "@/lib/constants";
import {
  Activity,
  ArrowRight,
  BookOpen,
  Box,
  Bug,
  FileJson,
  FlaskConical,
  GitFork,
  Layers,
  Server,
  Cpu,
  Database,
  ChevronRight,
  ExternalLink,
} from "lucide-react";

// ── Types ──────────────────────────────────────────────────

interface Module {
  title: string;
  description: string;
  path: string;
  icon: React.ElementType;
  color: string;
}

const modules: Module[] = [
  {
    title: "Requirement Analysis",
    description: "Transform product requirements into structured test cases, boundary values, and edge cases via AI.",
    path: ROUTES.REQUIREMENT_ANALYSIS,
    icon: FileJson,
    color: "from-cyan-500/20 to-blue-500/5",
  },
  {
    title: "API Test Generation",
    description: "Paste an OpenAPI spec and get ready-to-run pytest test suites generated by AI.",
    path: ROUTES.API_TEST_GENERATION,
    icon: FlaskConical,
    color: "from-violet-500/20 to-purple-500/5",
  },
  {
    title: "Failure Analysis",
    description: "Analyze CI/CD logs, stack traces, and error output for AI-powered root cause detection.",
    path: ROUTES.FAILURE_ANALYSIS,
    icon: Bug,
    color: "from-emerald-500/20 to-teal-500/5",
  },
];

// ── Links for docs / resources ─────────────────────────────

const resourceLinks = [
  {
    label: "GitHub Repository",
    href: "https://github.com/CypherMorgan/qpilot",
    icon: GitFork,
  },
  {
    label: "Architecture Docs",
    href: "https://github.com/CypherMorgan/qpilot/tree/master/docs",
    icon: BookOpen,
  },
];

// ── Architecture layers ────────────────────────────────────

const layers = [
  {
    label: "AI Features",
    items: ["Requirement Analysis", "API Test Generation", "Failure Analysis"],
    icon: Layers,
    color: "text-primary",
  },
  {
    label: "AI Infrastructure",
    items: ["Provider Registry", "Prompt Manager", "Response Validator"],
    icon: Cpu,
    color: "text-secondary",
  },
  {
    label: "Platform",
    items: ["FastAPI + PostgreSQL", "React + Vite + TanStack Query", "Docker Compose"],
    icon: Server,
    color: "text-accent",
  },
];

// ── Component ──────────────────────────────────────────────

export function HomePage() {
  const navigate = useNavigate();
  const { data: health, isLoading, isError } = useHealth();

  return (
    <div className="mx-auto max-w-6xl space-y-12 p-6 pb-16">
      {/* ── Hero ─────────────────────────────────────────── */}
      <section className="relative overflow-hidden rounded-2xl border bg-card p-8 md:p-12">
        {/* Blob decorations */}
        <div
          className="pointer-events-none absolute -right-20 -top-20 h-72 w-72 animate-blob rounded-full opacity-[0.08] dark:opacity-[0.12]"
          style={cssProps({ background: "var(--color-primary, hsl(197,100%,50%))", "--blob-duration": "14s" })}
          aria-hidden="true"
        />
        <div
          className="pointer-events-none absolute -bottom-24 -left-24 h-80 w-80 animate-blob rounded-full opacity-[0.06] dark:opacity-[0.10]"
          style={cssProps({ background: "var(--color-accent, hsl(187,100%,33%))", "--blob-duration": "18s", animationDelay: "2s" })}
          aria-hidden="true"
        />

        <div className="relative">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/5 px-3 py-1 text-xs font-medium text-primary">
            <Cpu className="h-3 w-3" />
            v{APP_VERSION}
          </div>
          <h1 className="text-3xl font-bold tracking-tight md:text-4xl">
            Welcome to {APP_NAME}
          </h1>
          <p className="mt-3 max-w-2xl text-base text-muted-foreground md:text-lg">
            An AI-augmented quality engineering platform that helps QA engineers and
            SDETs analyze requirements, generate API test suites, and diagnose
            automation failures — using AI as an accelerator, not a crutch.
          </p>
          <div className="mt-6 flex flex-wrap gap-3">
            <Button onClick={() => navigate(ROUTES.REQUIREMENT_ANALYSIS)}>
              <FileJson className="mr-2 h-4 w-4" />
              Get Started
              <ChevronRight className="ml-1 h-4 w-4" />
            </Button>
            <Button variant="outline" onClick={() => navigate(ROUTES.SETTINGS)}>
              <Activity className="mr-2 h-4 w-4" />
              Settings
            </Button>
          </div>
        </div>
      </section>

      {/* ── System Status ────────────────────────────────── */}
      <section>
        <div className="mb-4 flex items-center gap-2">
          <Server className="h-4 w-4 text-muted-foreground" />
          <h2 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">
            System Status
          </h2>
        </div>

        {isLoading && <LoadingState message="Checking backend connection..." />}

        {isError && (
          <div className="rounded-xl border border-destructive/20 bg-destructive/5 p-6 text-center">
            <Server className="mx-auto h-8 w-8 text-destructive/60" />
            <p className="mt-2 text-sm font-medium text-destructive">Backend Unavailable</p>
            <p className="mt-1 text-xs text-muted-foreground">
              Running in preview mode — some features require a backend connection.
            </p>
          </div>
        )}

        {health && (
          <div className="grid gap-3 sm:grid-cols-4">
            <StatusCard
              icon={<Activity className="h-4 w-4" />}
              label="Status"
              value={health.status}
              color="text-emerald-500"
            />
            <StatusCard
              icon={<Database className="h-4 w-4" />}
              label="Database"
              value={health.checks.database.status}
              meta={`${health.checks.database.latency_ms}ms`}
              color="text-emerald-500"
            />
            <StatusCard
              icon={<Cpu className="h-4 w-4" />}
              label="AI Provider"
              value={health.active_provider ?? "—"}
              meta={health.active_model ?? ""}
            />
            <StatusCard
              icon={<Server className="h-4 w-4" />}
              label="Version"
              value={health.app_version}
              meta="latest"
              mono
            />
          </div>
        )}
      </section>

      {/* ── Modules ──────────────────────────────────────── */}
      <section>
        <div className="mb-4 flex items-center gap-2">
          <Box className="h-4 w-4 text-muted-foreground" />
          <h2 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">
            Modules
          </h2>
        </div>

        <div className="grid gap-4 md:grid-cols-3">
          {modules.map((mod) => (
            <button
              key={mod.path}
              type="button"
              onClick={() => navigate(mod.path)}
              className={cn(
                "group relative w-full overflow-hidden rounded-xl border bg-card p-5 text-left transition-all",
                "hover:border-primary/30 hover:shadow-sm hover:shadow-primary/5",
                "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
              )}
            >
              {/* Gradient bg accent */}
              <div
                className={cn(
                  "pointer-events-none absolute inset-0 bg-gradient-to-br opacity-0 transition-opacity group-hover:opacity-100",
                  mod.color,
                )}
                aria-hidden="true"
              />
              <div className="relative">
                <div className="mb-3 flex h-10 w-10 items-center justify-center rounded-lg border bg-muted/50">
                  <mod.icon className="h-5 w-5" />
                </div>
                <h3 className="font-semibold">{mod.title}</h3>
                <p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">
                  {mod.description}
                </p>
                <div className="mt-4 flex items-center gap-1 text-xs font-medium text-primary opacity-0 transition-opacity group-hover:opacity-100">
                  Open module
                  <ArrowRight className="h-3 w-3" />
                </div>
              </div>
            </button>
          ))}
        </div>
      </section>

      {/* ── Architecture ─────────────────────────────────── */}
      <section>
        <div className="mb-4 flex items-center gap-2">
          <Layers className="h-4 w-4 text-muted-foreground" />
          <h2 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">
            Architecture
          </h2>
        </div>

        <div className="grid gap-4 md:grid-cols-3">
          {layers.map((layer) => (
            <div
              key={layer.label}
              className="rounded-xl border bg-card p-5"
            >
              <layer.icon className={cn("mb-3 h-5 w-5", layer.color)} />
              <h3 className="mb-2 text-sm font-semibold">{layer.label}</h3>
              <ul className="space-y-1.5">
                {layer.items.map((item) => (
                  <li
                    key={item}
                    className="flex items-center gap-2 text-xs text-muted-foreground"
                  >
                    <span className="h-1 w-1 rounded-full bg-muted-foreground/30" />
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        <details className="group mt-4 rounded-xl border bg-card">
          <summary className="flex cursor-pointer items-center gap-2 p-4 text-sm font-medium text-muted-foreground hover:text-foreground">
            <ChevronRight className="h-4 w-4 transition-transform group-open:rotate-90" />
            Full project structure
          </summary>
          <div className="border-t border-border px-4 pb-4 pt-3">
            <pre className="overflow-x-auto text-xs leading-relaxed text-muted-foreground"><code>{`app/
├── ai/                  # AI infrastructure layer
├── api/                 # REST API routes
├── infrastructure/      # Database, models, repositories
├── modules/
│   ├── requirement_analysis/
│   ├── api_test_generation/
│   └── failure_analysis/
├── config.py
└── main.py

frontend/
├── src/
│   ├── modules/         # Feature pages & components
│   ├── components/      # Shared UI components
│   ├── services/        # API client
│   └── layouts/         # App shell, sidebar

prompts/
├── analysis/            # AI prompt templates
└── shared/

docs/                    # ADRs & guides`}</code></pre>
          </div>
        </details>
      </section>

      {/* ── Resources & Docs ─────────────────────────────── */}
      <section>
        <div className="mb-4 flex items-center gap-2">
          <BookOpen className="h-4 w-4 text-muted-foreground" />
          <h2 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">
            Resources
          </h2>
        </div>

        <div className="grid gap-3 sm:grid-cols-2">
          {resourceLinks.map(({ label, href, icon: Icon }) => (
            <a
              key={label}
              href={href}
              target="_blank"
              rel="noopener noreferrer"
              className={cn(
                "flex items-center gap-3 rounded-xl border bg-card p-4 text-sm transition-all",
                "hover:border-primary/30 hover:shadow-sm",
              )}
            >
              <Icon className="h-5 w-5 shrink-0 text-muted-foreground" />
              <span className="flex-1 font-medium">{label}</span>
              <ExternalLink className="h-3.5 w-3.5 shrink-0 text-muted-foreground/50" />
            </a>
          ))}
        </div>
      </section>

      {/* ── Version footer ──────────────────────────────── */}
      <div className="border-t border-border pt-6 text-center text-xs text-muted-foreground">
        <p>
          {APP_NAME} v{APP_VERSION} &mdash; Built with FastAPI, React, and AI
        </p>
      </div>
    </div>
  );
}

// ── Sub-components ─────────────────────────────────────────

function StatusCard({
  icon,
  label,
  value,
  meta,
  color,
  mono,
}: {
  icon: React.ReactNode;
  label: string;
  value: string;
  meta?: string;
  color?: string;
  mono?: boolean;
}) {
  return (
    <div className="rounded-xl border bg-card p-4">
      <div className="flex items-center gap-2 text-xs text-muted-foreground">
        {icon}
        <span>{label}</span>
      </div>
      <p className={cn("mt-1.5 text-base font-semibold", color, mono && "font-mono tracking-tight")}>
        {value}
      </p>
      {meta && <p className="mt-0.5 text-[11px] text-muted-foreground">{meta}</p>}
    </div>
  );
}
