"""PyTest test file generator.

Generates the structural scaffolding for API test suites:
- ``conftest.py`` with shared fixtures (client, auth headers)
- ``README.md`` with setup instructions

The actual test functions are AI-generated and stored as file
content in the session's ``output_data``.  This module provides
the structural wrapper and ZIP packaging.
"""

from __future__ import annotations

import base64
import io
import zipfile
from datetime import datetime
from typing import Any

from app.modules.api_test_generation.exporters.base import TestExporter


class PytestGenerator(TestExporter):
    """Generates PyTest scaffolding files and ZIP archives."""

    def generate_conftest(
        self,
        servers: list[str],
        security_schemes: dict[str, Any],
    ) -> str:
        """Generate conftest.py with shared fixtures.

        Produces an async httpx client fixture configured with the
        API's base URL, plus auth headers from the spec's security
        schemes.
        """
        base_url = servers[0] if servers else "http://localhost:8000"
        lines: list[str] = [
            '"""Shared test fixtures for auto-generated API tests.',
            "",
            f"Generated by QPilot on {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"Server: {base_url}",
            '"""',
            "",
            "from __future__ import annotations",
            "",
            "from typing import Any",
            "",
            "import httpx",
            "import pytest",
            "",
        ]

        # Async client fixture
        lines.extend([
            "",
            "@pytest.fixture",
            "async def client() -> httpx.AsyncClient:",
            '    """Provide an async HTTP client pre-configured with the API base URL.',
            "",
            "    Usage in tests::",
            "",
            "        async def test_something(client: httpx.AsyncClient, auth_headers: dict) -> None:",
            '            response = await client.get("/endpoint", headers=auth_headers)',
            '    """',
            f'    async with httpx.AsyncClient(base_url="{base_url}") as _client:',
            "        yield _client",
            "",
        ])

        # Auth headers fixture
        auth_header_lines = self._generate_auth_fixture(security_schemes)
        lines.extend(auth_header_lines)

        return "\n".join(lines)

    def generate_readme(
        self,
        spec_title: str,
        spec_version: str,
        servers: list[str],  # noqa: ARG002 — kept for API consistency
        endpoint_count: int,
    ) -> str:
        """Generate a README with setup instructions."""
        lines = [
            f"# API Tests: {spec_title} v{spec_version}",
            "",
            f"Auto-generated PyTest suite for the **{spec_title}** API (v{spec_version}).",
            "",
            f"Covers **{endpoint_count}** endpoint(s).",
            "",
            "## Prerequisites",
            "",
            "- Python 3.9+",
            "- `pip install pytest httpx pytest-asyncio`",
            "",
            "## Setup",
            "",
            "1. Install dependencies:",
            "",
            "```bash",
            "pip install pytest httpx pytest-asyncio",
            "```",
            "",
            "2. Configure the API base URL in `conftest.py` (default: `{base_url}`).",
            "",
            "3. Set authentication credentials in `conftest.py` or via environment variables.",
            "",
            "## Running Tests",
            "",
            "```bash",
            "# Run all tests",
            "pytest",
            "",
            "# Run with verbose output",
            "pytest -v",
            "",
            "# Run a specific test file",
            "pytest test_pets.py",
            "",
            "# Run with markers",
            "pytest -m asyncio",
            "```",
            "",
            "## Test Structure",
            "",
            "- `conftest.py` — shared fixtures (client, auth headers)",
            "- `test_*.py` — test functions organized by API resource/tag",
            "",
            "## Notes",
            "",
            "- Tests use `httpx.AsyncClient` for async HTTP calls.",
            "- Authentication is configured in `conftest.py`. Update the token/credentials before running.",
            "- Some tests may fail if the API environment differs from the spec (e.g., test data may not exist).",
            "- The test suite is regeneratable — run the QPilot generator again when the spec changes.",
            "",
        ]
        return "\n".join(lines)

    def build_zip(
        self,
        conftest_content: str,
        readme_content: str,
        test_files: list[dict[str, str]],
    ) -> bytes:
        """Package generated files into a ZIP archive in memory.

        Args:
            conftest_content: Source code for conftest.py.
            readme_content: README content in Markdown.
            test_files: List of ``{"filename": ..., "content": ...}`` dicts.

        Returns:
            ZIP archive as bytes.
        """
        buffer = io.BytesIO()
        with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
            zf.writestr("generated-tests/conftest.py", conftest_content)
            zf.writestr("generated-tests/README.md", readme_content)
            for tf in test_files:
                zf.writestr(f"generated-tests/{tf['filename']}", tf["content"])
        return buffer.getvalue()

    def decode_zip_content(self, content: str) -> bytes:
        """Decode base64-encoded ZIP content stored in the database."""
        return base64.b64decode(content)

    def encode_zip_content(self, zip_bytes: bytes) -> str:
        """Encode ZIP bytes as base64 for database storage."""
        return base64.b64encode(zip_bytes).decode("ascii")

    # ── Private helpers ───────────────────────────────────────────

    def _generate_auth_fixture(self, security_schemes: dict[str, Any]) -> list[str]:
        """Generate the auth_headers fixture based on security schemes."""
        lines = [
            "",
            "@pytest.fixture",
            "def auth_headers() -> dict[str, str]:",
            '    """Provide authentication headers as defined in the API spec.',
            "",
        ]

        if not security_schemes:
            lines.extend([
                "    No security schemes defined in the spec.",
                "    Returns an empty dict — add credentials before running tests.",
                '    """',
                "    return {}",
                "",
            ])
            return lines

        lines.append("    Update the placeholder values with real credentials before running tests.")
        lines.append('    """')

        # Generate header entries
        header_entries: list[str] = []
        for _scheme_name, scheme in security_schemes.items():
            if scheme.type == "http" and scheme.scheme == "bearer":
                header_entries.append('    "Authorization": "Bearer <your-token>",')
            elif scheme.type == "apiKey" and scheme.in_ == "header":
                key_name = scheme.name or "X-API-Key"
                header_entries.append(f'    "{key_name}": "<your-api-key>",')
            elif scheme.type == "http" and scheme.scheme == "basic":
                lines.append(
                    '    # Basic auth: encode credentials before passing to headers'
                )

        if header_entries:
            lines.append("    return {")
            lines.extend(header_entries)
            lines.append("    }")
        else:
            lines.append("    return {}")
        lines.append("")

        return lines
